// <auto-generated />
namespace CEN511_Covid19.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class _5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_5));
        
        string IMigrationMetadata.Id
        {
            get { return "202012060723596_5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
